In [1]:
lst = [4,8,6,54,9]

In [2]:
type (lst)

list

In [3]:
import numpy as np

In [4]:
arr1 = np.array ([45,89,96,87,23,47])

In [5]:
arr1

array([45, 89, 96, 87, 23, 47])

In [6]:
arr1

array([45, 89, 96, 87, 23, 47])

In [7]:
type (arr1)

numpy.ndarray

In [8]:
lst

[4, 8, 6, 54, 9]

In [9]:
arr2 = np.array (lst)

In [10]:
arr2

array([ 4,  8,  6, 54,  9])

In [11]:
arr1

array([45, 89, 96, 87, 23, 47])

In [12]:
arr1.shape

(6,)

In [16]:
arr3 =  np.array([[23,45,6],[45,67,9],[45,78,23]]) 

In [17]:
arr3

array([[23, 45,  6],
       [45, 67,  9],
       [45, 78, 23]])

In [18]:
arr3.shape

(3, 3)

In [19]:
arr4 = np.array ([[2,4],[3,5],[6,89]])

In [20]:
arr4

array([[ 2,  4],
       [ 3,  5],
       [ 6, 89]])

In [21]:
arr4.shape

(3, 2)

In [22]:
range (0,10)

range(0, 10)

In [28]:
range1 = np.arange (0,11)

In [29]:
range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange (0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
np.arange (0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.arange (0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [33]:
np.zeros (3)

array([0., 0., 0.])

In [34]:
np.zeros (6)

array([0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros ((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones (9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.ones ((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.ones ((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye (6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
np.linspace (1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
np.linspace (1,5,2)

array([1., 5.])

In [44]:
np.random.rand(5)

array([0.316612  , 0.92469226, 0.75502764, 0.7930171 , 0.61173404])

In [45]:
np.random.rand(4,5)

array([[0.01455586, 0.53653261, 0.15406743, 0.31553964, 0.74120489],
       [0.06272583, 0.07620258, 0.06980741, 0.6799205 , 0.68109534],
       [0.77545208, 0.30377825, 0.48267454, 0.9299298 , 0.01843578],
       [0.44813938, 0.62476662, 0.84877604, 0.27140714, 0.17500578]])

In [46]:
np.random.randint (1,20)

14

In [47]:
np.random.randint (1,100)

63

In [48]:
np.random.randint (1,100,10)

array([75, 54, 71, 95,  6, 25,  4, 17, 41, 49])

In [49]:
arr5 = np.random.randint (1,100,10)

In [50]:
arr5

array([33, 66,  4, 24,  6, 64, 94,  6, 89, 53])

In [51]:
arr5.shape

(10,)

In [52]:
arr5.reshape (2,5)

array([[33, 66,  4, 24,  6],
       [64, 94,  6, 89, 53]])

In [53]:
arr5.reshape (5,2)

array([[33, 66],
       [ 4, 24],
       [ 6, 64],
       [94,  6],
       [89, 53]])

In [54]:
arr5.reshape (10,1)

array([[33],
       [66],
       [ 4],
       [24],
       [ 6],
       [64],
       [94],
       [ 6],
       [89],
       [53]])

In [55]:
arr6 = np.arange (25)

In [56]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr6.shape

(25,)

In [58]:
arr6.reshape (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr6.reshape (25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [60]:
arr7 = np.array ([12,4,78,96,1,87,56,34,25])

In [61]:
arr7

array([12,  4, 78, 96,  1, 87, 56, 34, 25])

In [62]:
arr7.shape

(9,)

In [64]:
arr7.max()

96

In [65]:
arr7.min()

1

In [66]:
arr7

array([12,  4, 78, 96,  1, 87, 56, 34, 25])

In [68]:
arr7.argmax ()

3

In [69]:
arr7.argmin()

4

In [70]:
arr7

array([12,  4, 78, 96,  1, 87, 56, 34, 25])

In [71]:
arr7[5]

87

In [72]:
arr7 [2:5]

array([78, 96,  1])

In [73]:
arr7 [0:3]

array([12,  4, 78])

In [74]:
arr7 [: 3]

array([12,  4, 78])

In [75]:
arr7 [2 :]

array([78, 96,  1, 87, 56, 34, 25])

In [76]:
arr7 [2:5]

array([78, 96,  1])

In [77]:
arr7 [2:5] = 100

In [78]:
arr7

array([ 12,   4, 100, 100, 100,  87,  56,  34,  25])

In [79]:
arr8 = np.array ([[2,4,6],[23,45,67],[27,49,10]])

In [80]:
arr8

array([[ 2,  4,  6],
       [23, 45, 67],
       [27, 49, 10]])

In [81]:
arr8.shape

(3, 3)

In [82]:
arr8 [0]

array([2, 4, 6])

In [83]:
arr8 [2]

array([27, 49, 10])

In [84]:
arr8

array([[ 2,  4,  6],
       [23, 45, 67],
       [27, 49, 10]])

In [85]:
arr8 [0] [0]

2

In [86]:
arr8 [2] [0]

27

In [87]:
arr8 [0:2,0:2]

array([[ 2,  4],
       [23, 45]])

In [88]:
arr8

array([[ 2,  4,  6],
       [23, 45, 67],
       [27, 49, 10]])

In [89]:
arr8 [1:,0:2]

array([[23, 45],
       [27, 49]])

In [90]:
arr8

array([[ 2,  4,  6],
       [23, 45, 67],
       [27, 49, 10]])

In [91]:
arr8 [1:]

array([[23, 45, 67],
       [27, 49, 10]])

In [92]:
arr8 [1:,1:]

array([[45, 67],
       [49, 10]])